### PR TITLE
add one more banner

### PR DESCRIPTION
**Pull request by jerryan999**

### CODE REVIEW

**Comment by jerryan999** [comment]
@hethune

**Comment by jerryan999** [comment]
v3 - api
```
{
  "carouse_figure": [
    {
      "external_link": null, 
      "index": 1, 
      "pic_url": "http://ot2sj5ee6.bkt.clouddn.com/image/home/banner_1.jpg?e=1505465192&token=GlYeQvaN6jtwlUpwV9iyFJiSq9_JEOppgpEGD3Ol:Jnt2c2FrO9T3P5ZYlR4SwPfatdA="
    }, 
    {
      "external_link": null, 
      "index": 2, 
      "pic_url": "http://ot2sj5ee6.bkt.clouddn.com/image/home/banner_2.jpg?e=1505465192&token=GlYeQvaN6jtwlUpwV9iyFJiSq9_JEOppgpEGD3Ol:MgJxBmWpwWvmRu4VLXxRJlggfJ0="
    }, 
    {
      "external_link": null, 
      "index": 3, 
      "pic_url": "http://ot2sj5ee6.bkt.clouddn.com/image/home/banner_3.jpg?e=1505465192&token=GlYeQvaN6jtwlUpwV9iyFJiSq9_JEOppgpEGD3Ol:oVpe0wG0xZ-f7AS6__Pv1-kZExY="
    }, 
    {
      "external_link": "http://zc-test.wehome.io", 
      "index": 4, 
      "pic_url": "http://ot2sj5ee6.bkt.clouddn.com/image/home/banner4.jpg?e=1505465192&token=GlYeQvaN6jtwlUpwV9iyFJiSq9_JEOppgpEGD3Ol:To5EI-WKFIu54qFZCIeFTbU83ik="
    }
  ], 
  "success": true
}

```

**Comment by jerryan999** [comment]
v2-api
```
{
  "carouse_figure": [
    {
      "index": 1, 
      "pic_url": "http://ot2sj5ee6.bkt.clouddn.com/image/home/banner1.jpg?e=1505465317&token=GlYeQvaN6jtwlUpwV9iyFJiSq9_JEOppgpEGD3Ol:fj7uUek1jj3wu9T_Z75r212x97E="
    }, 
    {
      "index": 2, 
      "pic_url": "http://ot2sj5ee6.bkt.clouddn.com/image/home/banner2.jpg?e=1505465317&token=GlYeQvaN6jtwlUpwV9iyFJiSq9_JEOppgpEGD3Ol:0OlFb05I442m5_j37QeG3Df1U8s="
    }, 
    {
      "index": 3, 
      "pic_url": "http://ot2sj5ee6.bkt.clouddn.com/image/home/banner3.jpg?e=1505465317&token=GlYeQvaN6jtwlUpwV9iyFJiSq9_JEOppgpEGD3Ol:-vC130rf0DFvlhDk4J_15ZeIphI="
    }
  ], 
  "success": true
}
```

**Comment by hethune** [comment]
LGTM

**Pull request merged**
